[project]
name = "console-todo-app"
version = "0.1.0"
dependencies = [
    "sqlmodel",
    "rich",
    "textual",
]

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-textual-snapshot",
]
